Add chapter 2 without the translation of the quiz
SigmoidAI/course pull request #3
Opened 2024-10-20 17:42 UTC by FriptuLudmila

2024-11-14 18:52 UTC, eduard-balamatiuc requested changes

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/1.mdx
> +</Tip>
```suggestion
<Tip>
⚠️ Pentru a beneficia de toate funcțiile disponibile cu Model Hub și 🤗 Transformers, vă recomandăm <a href="https://huggingface.co/join">să vă creați un cont</a>.
</Tip>
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/1.mdx
> +- ** Simplitate în utilizare**: Descărcarea, încărcarea și utilizarea unui model NLP de ultimă generație pentru inferență pot fi realizate în doar două linii de cod.
```suggestion
- **Simplitate în utilizare**: Descărcarea, încărcarea și utilizarea unui model NLP de ultimă generație pentru inferență pot fi realizate în doar două linii de cod.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/1.mdx
> +- **Simplitate**: Aproape că nu se fac abstractizări în întreaga bibliotecă. „All in one file” este un concept de bază: trecerea înainte a unui model este definită în întregime într-un singur fișier,
```suggestion
- **Simplitate**: Aproape că nu se fac abstractizări în întreaga bibliotecă. „All in one file” este un concept de bază: trecerea înainte a unui model este definită în întregime într-un singur fișier, astfel încât codul în sine să fie ușor de înțeles și de modificat.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/1.mdx
> +Această ultimă caracteristică face 🤗 Transformers destul de diferit de alte biblioteci ML. Modelele nu sunt construite pe module
```suggestion
Această ultimă caracteristică face ca 🤗 Transformers să fie destul de diferită de alte biblioteci ML. Modelele nu sunt construite pe module 
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +Să începem cu un exemplu complet, aruncând o privire la ceea ce s-a întâmplat în spate atunci când am executat următorul cod în [Capitolul 1](/curs/capitol1):
```suggestion
Să începem cu un exemplu complet, aruncând o privire la ceea ce s-a întâmplat în spate atunci când am executat următorul cod în [Capitolul 1](/course/chapter1):
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +Deși aceste stări ascunse pot fi utile pe cont propriu, ele sunt de obicei intrări pentru o altă parte a modelului, cunoscută sub numele de *head*. În [Capitolul 1](/curs/capitol1), diferitele sarcin
```suggestion
Deși aceste stări ascunse pot fi utile pe cont propriu, ele sunt de obicei intrări pentru o altă parte a modelului, cunoscută sub numele de *head*. În [Capitolul 1](/course/chapter1), diferitele sarcini ar fi putut fi efectuate cu aceeași arhitectură, dar fiecăreia dintre aceste sarcini îi va fi asociat un head diferit.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +## Preprocesarea cu un tokenizator[[preprocesarea-cu-un-tokenizerator]]
```suggestion
## Preprocesarea cu un tokenizator[[preprocesarea-cu-un-tokenizator]]
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +Toată această preprocesare trebuie efectuată exact în același mod ca atunci când modelul a fost preinstruit, așa că mai întâi trebuie să descărcăm aceste informații din [Model Hub] (https://huggingfa
```suggestion
Toată această preprocesare trebuie efectuată exact în același mod ca atunci când modelul a fost preinstruit, așa că mai întâi trebuie să descărcăm aceste informații din [Model Hub](https://huggingface.co/models). Pentru a face acest lucru, folosim clasa `AutoTokenizer` și metoda sa `from_pretrained()`. Folosind numele checkpoint-ului modelului nostru, aceasta va prelua automat datele asociate cu tokenizer-ul modelului și le va stoca în cache (astfel încât acestea să fie descărcate doar prima dată când executați codul de mai jos).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +Puteți utiliza 🤗 Transformers fără a trebui să vă faceți griji cu privire la cadrul ML utilizat ca backend; ar putea fi PyTorch sau TensorFlow, sau Flax pentru unele modele. Cu toate acestea, modelel
```suggestion
Puteți utiliza 🤗 Transformers fără a trebui să vă faceți griji cu privire la cadrul ML utilizat ca backend; ar putea fi PyTorch sau TensorFlow, sau Flax pentru unele modele. Cu toate acestea, modelele Transformer acceptă numai *tensori * ca intrare. Dacă este prima dată când auziți despre tensori, vă puteți gândi la ei ca la array-uri NumPy. Un array NumPy poate fi un scalar (0D), un vector (1D), o matrice (2D) sau poate avea mai multe dimensiuni. Este de fapt un tensor; tensorii altor cadre ML se comportă similar și sunt de obicei la fel de simplu de instanțiat ca și array-urile NumPy.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +Nu vă faceți încă griji cu privire la padding și trunchiere; le vom explica mai târziu. Principalele lucruri de reținut aici sunt că puteți trece o propoziție sau o listă de propoziții, precum și spe
```suggestion
Nu vă faceți încă griji cu privire la padding și trunchiere; le vom explica mai târziu. Principalele lucruri de reținut aici sunt că puteți trece o propoziție sau o listă de propoziții, precum și specificarea tipului de tensori pe care doriți să îi primiți înapoi (dacă nu este trecut niciun tip, veți primi o listă de liste ca rezultat).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +Această arhitectură conține doar modulul Transformer de bază: având în vedere anumite intrări, acesta produce ceea ce vom numi *stări ascunse*, cunoscute și ca *caracteristici*. Pentru fiecare intrar
```suggestion
Această arhitectură conține doar modulul Transformer de bază: având în vedere anumite intrări, acesta produce ceea ce vom numi *stări ascunse*, cunoscute și ca *caracteristici*. Pentru fiecare intrare a modelului, vom extrage un vector multidimensional care reprezintă **înțelegerea contextuală a intrării respective de către modelul Transformer**.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +### Modele de head-uri: Înțelegerea numerelor[modele-de-head-uri-înțelegerea-numerelor]]
```suggestion
### Modele de head-uri: Înțelegerea numerelor[[modele-de-head-uri-înțelegerea-numerelor]]
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +- Prima propoziție: NEGATIV: 0,0402, POZITIV: 0,9598
```suggestion
- Prima propoziție: NEGATIV: 0.0402, POZITIV: 0.9598
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +- A doua propoziție: NEGATIVĂ: 0,9995, POZITIVĂ: 0,0005
```suggestion
- A doua propoziție: NEGATIVĂ: 0.9995, POZITIVĂ: 0.0005
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +** Încercați!** Alegeți două (sau mai multe) texte proprii și treceți-le prin conducta `sentiment-analysis`. Apoi repetați pașii pe care i-ați văzut aici și verificați dacă obțineți aceleași rezultat
```suggestion
**Încercați!** Alegeți două (sau mai multe) texte proprii și treceți-le prin conducta `sentiment-analysis`. Apoi repetați pașii pe care i-ați văzut aici și verificați dacă obțineți aceleași rezultate!
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +</Tip>
```suggestion
<Tip>

✏️  ** Încercați!** Alegeți două (sau mai multe) texte proprii și treceți-le prin conducta `sentiment-analysis`. Apoi repetați pașii pe care i-ați văzut aici și verificați dacă obțineți aceleași rezultate!

</Tip>
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +Modelul poate fi utilizat în această stare, dar va produce rezultate neclare; mai întâi trebuie să fie antrenat. Am putea antrena modelul de la zero pentru sarcina în cauză, dar, după cum ați văzut î
```suggestion
Modelul poate fi utilizat în această stare, dar va produce rezultate neclare; mai întâi trebuie să fie antrenat. Am putea antrena modelul de la zero pentru sarcina în cauză, dar, după cum ați văzut în [Capitolul 1](/course/chapter1), acest lucru ar necesita mult timp și o mulțime de date și ar avea un impact semnificativ asupra mediului. Pentru a evita efortul inutil, este esențial să puteți partaja și reutiliza modelele care au fost deja antrenate.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +După cum ați văzut mai devreme, am putea înlocui `BertModel` cu clasa `AutoModel` echivalentă. Vom face acest lucru în continuare, deoarece acest lucru produce un cod compatibil cu checkpoint-urile;
```suggestion
După cum ați văzut mai devreme, am putea înlocui `BertModel` cu clasa `AutoModel` echivalentă. Vom face acest lucru în continuare, deoarece acest lucru produce un cod compatibil cu checkpoint-urile; dacă codul dumneavoastră funcționează pentru un checkpoint, ar trebui să funcționeze fără probleme pentru altul. Acest lucru este valabil chiar dacă arhitectura este diferită, atât timp cât checkpoint-ul a fost antrenat pentru o sarcină similară (de exemplu, o sarcină de analiză a sentimentelor).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +Încărcarea unui model Transformer care este deja instruit este simplă - putem face acest lucru utilizând metoda `from_pr
```suggestion
Încărcarea unui model Transformer care este deja antrenat este simplă - putem face acest lucru utilizând metoda `from_pr
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +Putem descărca modelul nostru preinstruit în același mod în care am făcut-o cu tokenizatorul nostru. 🤗 Transformers oferă o clasă `AutoModel` care are și o metodă `from_pretrained()`:
```suggestion
Putem descărca modelul nostru preantrenat în același mod în care am făcut-o cu tokenizatorul nostru. 🤗 Transformers oferă o clasă `AutoModel` care are și o metodă `from_pretrained()`:
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +Putem descărca modelul nostru preinstruit în același mod în care am făcut-o cu tokenizatorul nostru. 🤗 Transformers oferă o clasă `TFAutoModel` care are și o metodă `from_pretrained`:
```suggestion
Putem descărca modelul nostru preantrenat în același mod în care am făcut-o cu tokenizatorul nostru. 🤗 Transformers oferă o clasă `TFAutoModel` care are și o metodă `from_pretrained`:
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +După cum ați văzut mai devreme, am putea înlocui `BertModel` cu clasa `AutoModel` echivalentă. Vom face acest lucru în continuare, deoarece acest lucru produce un cod compatibil cu checkpoint-urile;
```suggestion
După cum ați văzut mai devreme, am putea înlocui `BertModel` cu clasa `AutoModel` echivalentă. Vom face acest lucru în continuare, deoarece acest lucru produce un cod compatibil cu checkpoint-urile; dacă codul dumneavoastră funcționează pentru un checkpoint, ar trebui să funcționeze fără probleme pentru altul. Acest lucru este valabil chiar dacă arhitectura este diferită, atât timp cât checkpoint-ul a fost antrenat pentru o sarcină similară (de exemplu, o sarcină de analiză a sentimentelor).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +În exemplul de cod de mai sus nu am utilizat `BertConfig` și, în loc de acesta, am încărcat un model preinstruit prin intermediul identificatorului `bert-base-cased`. Acesta este un checkpoint al mod
```suggestion
În exemplul de cod de mai sus nu am utilizat `BertConfig` și, în loc de acesta, am încărcat un model preantrenat prin intermediul identificatorului `bert-base-cased`. Acesta este un checkpoint al modelului care a fost antrenat chiar de autorii BERT; puteți găsi mai multe detalii despre acesta în [model card](https://huggingface.co/bert-base-cased).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +Acest model este acum inițializat cu toate weight-urile din checkpoint. Acesta poate fi utilizat direct pentru inferență pe sarcinile pe care a fost antrenat și poate fi, de asemenea, ajustat pe o sa
```suggestion
Acest model este acum inițializat cu toate weight-urile din checkpoint. Acesta poate fi utilizat direct pentru inferență pe sarcinile pe care a fost antrenat și poate fi, de asemenea, ajustat pe o sarcină nouă. Prin antrenarea cu weight-uri preantrenate în prealabil, putem obține rapid rezultate bune.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +Al doilea pas este să convertim aceste token-uri în numere, astfel încât să putem construi un tensor din ele și să le introducem în model. Pentru a face acest lucru, tokenizatorul are un *vocabular*,
```suggestion
Al doilea pas este să convertim aceste token-uri în numere, astfel încât să putem construi un tensor din ele și să le introducem în model. Pentru a face acest lucru, tokenizatorul are un *vocabular*, care este partea pe care o descărcăm atunci când îl instanțiem cu metoda `from_pretrained()`. Din nou, trebuie să folosim același vocabular utilizat atunci când modelul a fost preantrenat.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/6.mdx
> +Tokenizatorul a adăugat cuvântul special `[CLS]` la început și cuvântul special `[SEP]` la sfârșit. Acest lucru se datorează faptului că modelul a fost preinstruit cu aceste cuvinte, deci pentru a ob
```suggestion
Tokenizatorul a adăugat cuvântul special `[CLS]` la început și cuvântul special `[SEP]` la sfârșit. Acest lucru se datorează faptului că modelul a fost preantrenat cu aceste cuvinte, deci pentru a obține aceleași rezultate pentru inferență trebuie să le adăugăm și pe acestea. Rețineți că unele modele nu adaugă cuvinte speciale sau adaugă cuvinte diferite; de asemenea, modelele pot adăuga aceste cuvinte speciale doar la început sau doar la sfârșit. În orice caz, tokenizatorul știe care sunt cele așteptate și se va ocupa de acest lucru pentru dumneavoastră.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/1.mdx
> +Biblioteca 🤗 Transformers a fost creată pentru a rezolva această problemă. Scopul său este de a oferi un singur API prin care orice model Transformer poate fi încărcat, instruit și salvat. Principale
```suggestion
Biblioteca 🤗 Transformers a fost creată pentru a rezolva această problemă. Scopul său este de a oferi un singur API prin care orice model Transformer poate fi încărcat, antrenat și salvat. Principalele caracteristici ale bibliotecii sunt:
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +Toată această preprocesare trebuie efectuată exact în același mod ca atunci când modelul a fost preinstruit, așa că mai întâi trebuie să descărcăm aceste informații din [Model Hub] (https://huggingfa
```suggestion
Toată această preprocesare trebuie efectuată exact în același mod ca atunci când modelul a fost preantrenat, așa că mai întâi trebuie să descărcăm aceste informații din [Model Hub] (https://huggingface.co/models). Pentru a face acest lucru, folosim clasa `AutoTokenizer` și metoda sa `from_pretrained()`. Folosind numele checkpoint-ului modelului nostru, aceasta va prelua automat datele asociate cu tokenizer-ul modelului și le va stoca în cache (astfel încât acestea să fie descărcate doar prima dată când executați codul de mai jos).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +După cum ați văzut mai devreme, am putea înlocui `BertModel` cu clasa `AutoModel` echivalentă. Vom face acest lucru în continuare, deoarece acest lucru produce un cod compatibil cu checkpoint-urile;
```suggestion
După cum ați văzut mai devreme, am putea înlocui `BertModel` cu clasa `AutoModel` echivalentă. Vom face acest lucru în continuare, deoarece acest lucru produce un cod independent de checkpoint-uri; dacă codul dumneavoastră funcționează pentru un checkpoint, ar trebui să funcționeze fără probleme pentru altul. Acest lucru este valabil chiar dacă arhitectura este diferită, atât timp cât checkpoint-ul a fost instruit pentru o sarcină similară (de exemplu, o sarcină de analiză a sentimentelor).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +Identificatorul utilizat pentru încărcarea modelului poate fi identificatorul oricărui model de pe Model Hub, atâta timp cât acesta este compatibil cu arhitectura OARET. Lista completă a  checkpoint-
```suggestion
Identificatorul utilizat pentru încărcarea modelului poate fi identificatorul oricărui model de pe Model Hub, atâta timp cât acesta este compatibil cu arhitectura BERT. Lista completă a  checkpoint-urilor BERT disponibile poate fi găsită [aici](https://huggingface.co/models?filter=bert).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +### Metode de păstrare[[metode-de-păstrare]]
```suggestion
### Metode de salvare[[metode-de-salvare]]
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +### Utilizarea tensorilor ca intrări în model[[utilizarea-tensorilor-ca-intrări-în-to-model]]
```suggestion
### Utilizarea tensorilor ca intrări în model[[utilizarea-tensorilor-ca-intrări-în-model]]
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +Aceasta este o listă de secvențe codificate: o listă de liste. Tensorii acceptă numai forme dreptunghiulare (gândiți-vă la matrici). Această " listă " are deja o formă dreptunghiulară, astfel încât c
```suggestion
Aceasta este o listă de secvențe codificate: o listă de liste. Tensorii acceptă numai forme dreptunghiulare (gândiți-vă la matrici). Acest "array" are deja o formă dreptunghiulară, astfel încât convertirea sa într-un tensor este ușoară:
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/3.mdx
> +În exemplul de cod de mai sus nu am utilizat `BertConfig` și, în loc de acesta, am încărcat un model preinstruit prin intermediul identificatorului `bert-base-cased`. Acesta este un checkpoint al mod
```suggestion
În exemplul de cod de mai sus nu am utilizat `BertConfig` și, în loc de acesta, am încărcat un model preinstruit prin intermediul identificatorului `bert-base-cased`. Acesta este un checkpoint al modelului care a fost antrenat chiar de autorii BERT; puteți găsi mai multe detalii despre acesta în [fișa modelului](https://huggingface.co/bert-base-cased).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +Tokenizoarele sunt una dintre componentele de bază ale pipeline-ului NLP. Acestea au un singur scop: să transforme textul în date care pot fi prelucrate de model. Modelele pot procesa doar numere, as
```suggestion
Tokenizerii sunt unele dintre componentele de bază ale pipeline-ului NLP. Acestea au un singur scop: să transforme textul în date care pot fi prelucrate de model. Modelele pot procesa doar numere, astfel încât tokenizerii trebuie să convertească intrările noastre de text în date numerice. În această secțiune, vom explora exact ce se întâmplă în pipeline-ul de tokenizare. 
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +Algoritmii "Subword Tokenization " se bazează pe principiul conform căruia cuvintele utilizate frecvent nu ar trebui să fie împărțite în cuvinte secundare mai mici, dar cuvintele rare ar trebui să fi
```suggestion
Algoritmii "Subword Tokenization " se bazează pe principiul conform căruia cuvintele utilizate frecvent nu ar trebui să fie împărțite în subcuvinte mai mici, dar cuvintele rare ar trebui să fie descompuse în subcuvinte semnificative.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +Aceste părți de cuvinte oferă în cele din urmă o mulțime de semnificații semantice: în exemplul de mai sus, "tokenization" a fost împărțit în "token" și "ization", două cuvinte care au o semnificație
```suggestion
Aceste părți de cuvinte oferă în cele din urmă o mulțime de semnificații semantice: în exemplul de mai sus, "tokenization" a fost împărțit în "token" și "ization", doi tokenuri care au o semnificație semantică, fiind în același timp eficiente din punct de vedere al spațiului (sunt necesare doar două cuvinte pentru a reprezenta un cuvânt lung). Acest lucru ne permite să avem o acoperire relativ bună cu vocabulare de dimensiuni mici și aproape fără token-uri necunoscute.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +Aceste părți de cuvinte oferă în cele din urmă o mulțime de semnificații semantice: în exemplul de mai sus, "tokenization" a fost împărțit în "token" și "ization", două cuvinte care au o semnificație
```suggestion
Aceste subcuvinte oferă în cele din urmă o mulțime de semnificații semantice: în exemplul de mai sus, "tokenization" a fost împărțit în "token" și "ization", două cuvinte care au o semnificație semantică, fiind în același timp eficiente din punct de vedere al spațiului (sunt necesare doar două cuvinte pentru a reprezenta un cuvânt lung). Acest lucru ne permite să avem o acoperire relativ bună cu vocabulare de dimensiuni mici și aproape fără token-uri necunoscute.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +Această abordare este utilă în special în limbile aglutinative, cum ar fi turca, în care se pot forma cuvinte complexe (aproape) arbitrar de lungi prin combinarea părților de cuvinte.
```suggestion
Această abordare este utilă în special în limbile aglutinative, cum ar fi turca, în care se pot forma cuvinte complexe (aproape) arbitrar de lungi prin combinarea subcuvintelor.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +Acest tokenizator este un tokenizator de părți de cuvinte: împarte cuvintele până când obține token-uri care pot fi reprezentate de vocabularul său. Acesta este cazul aici cu `transformer`, care este
```suggestion
Acest tokenizator este un tokenizator de subcuvinte: împarte cuvintele până când obține token-uri care pot fi reprezentate de vocabularul său. Acesta este cazul aici cu `transformer`, care este împărțit în două token-uri: `transform` și `##er`
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +- Împărțirea datelor de intrare în cuvinte, părți de cuvinte sau simboluri (cum ar fi punctuația) care se numesc *tokens*
```suggestion
- Împărțirea datelor de intrare în cuvinte, subcuvinte sau simboluri (cum ar fi punctuația) care se numesc *tokens*
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +Acum ar trebui să cunoașteți destul de bine cum funcționează tokenizerele pentru a începe să utilizați API-
```suggestion
Acum ar trebui să cunoașteți destul de bine cum funcționează tokenizerele pentru a începe să utilizați API-ul.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +Încărcarea tokenizatorului BERT antrenat cu același punct de control ca BERT se face în același mod ca și încărcarea modelului, cu excepția faptului că folosim clasa `BertTokenizer`:
```suggestion
Încărcarea tokenizatorului BERT antrenat cu același checkpoint ca BERT se face în același mod ca și încărcarea modelului, cu excepția faptului că folosim clasa `BertTokenizer`:
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +
```suggestion

Traducerea textului în numere este cunoscută sub numele de codificare. Codificarea se face într-un proces în două etape: tokenizarea, urmată de conversia în ID-uri de intrare.

```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +Al doilea pas este să convertim aceste token-uri în numere, astfel încât să putem construi un tensor din ele și să le introducem în model. Pentru a face acest lucru, tokenizatorul are un *vocabular*,
```suggestion
După cum am văzut, primul pas este să împărțim textul în cuvinte (sau părți de cuvinte, semne de punctuație, etc.), deobicei numite *tokens*. Există mai multe reguli care pot guverna acest proces, motiv pentru care trebuie să inițiem tokenizerul folosind numele modelului, pentru a ne asigura că utilizăm aceleași reguli care au fost utilizate atunci când modelul a fost preantrenat.

Al doilea pas este să convertim aceste token-uri în numere, astfel încât să putem construi un tensor din ele și să le introducem în model. Pentru a face acest lucru, tokenizatorul are un *vocabular*, care este partea pe care o descărcăm atunci când îl instanțiem cu metoda `from_pretrained()`. Din nou, trebuie să folosim același vocabular utilizat atunci când modelul a fost preinstruit.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/4.mdx
> +✏️ ** Încercați!** Replicați ultimii doi pași (tokenizarea și conversia în ID-uri de intrare) pe propozițiile de intrare pe care le-am folosit în secțiunea 2 ("I've been waiting for a HuggingFace cou
```suggestion
✏️ **Încercați!** Replicați ultimii doi pași (tokenizarea și conversia în ID-uri de intrare) pe propozițiile de intrare pe care le-am folosit în secțiunea 2 ("I've been waiting for a HuggingFace course my whole life." și "I hate this so much!"). Verificați dacă obțineți aceleași ID-uri de intrare pe care le-am obținut mai devreme! 
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +Gruparea în loturi este acțiunea de a trimite mai multe propoziții prin model, toate odată. Dacă aveți o singură propoziție, puteți crea un lot cu o singură secvență:
```suggestion
Batching-ul este acțiunea de a trimite mai multe propoziții prin model, toate odată. Dacă aveți o singură propoziție, puteți crea un lot cu o singură secvență: 
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +Gruparea în loturi permite modelului să funcționeze atunci când îi furnizați mai multe secvențe. Utilizarea mai multor secvențe este la fel de simplă ca și crearea unui lot cu o singură secvență. Exi
```suggestion
Batching-ul permite modelului să funcționeze atunci când îi furnizați mai multe secvențe. Utilizarea mai multor secvențe este la fel de simplă ca și crearea unui lot cu o singură secvență. Există însă o a doua problemă. Atunci când încercați să combinați două (sau mai multe) propoziții, acestea pot avea lungimi diferite. Dacă ați mai lucrat vreodată cu tensori, știți că aceștia trebuie să aibă o formă dreptunghiulară, deci nu veți putea converti direct lista de ID-uri de intrare într-un tensor. Pentru a rezolva această problemă, de obicei *umplem* datele de intrare.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +## Umplerea datelor de intrare[[umplerea-datelor-de-intrare]]
```suggestion
## Padding-ul datelor de intrare[[padding-ul-datelor-de-intrare]]
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +ID-ul token-ului de umplere poate fi găsit în `tokenizer.pad_token_id`. Să-l folosim și să trimitem cele două propoziții prin model în mod separat și grupate împreună:
```suggestion
ID-ul token-ului de padding poate fi găsit în `tokenizer.pad_token_id`. Să-l folosim și să trimitem cele două propoziții prin model în mod separat și grupate împreună:
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +Observăm cum ultima valoare a celei de-a doua secvențe este un ID de umplere, care este o valoare 0 în masca de atenție.
```suggestion
Observăm cum ultima valoare a celei de-a doua secvențe este un ID de padding, care este o valoare 0 în masca de atenție.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +✏️ ** Încercați!** Aplicați manual tokenizarea pe cele două propoziții utilizate în secțiunea 2 ("I've been waiting for a HuggingFace course my whole life." și "I hate this so much!"). Treceți-le pri
```suggestion
✏️ ** Încercați!** Aplicați manual tokenizarea pe cele două propoziții utilizate în secțiunea 2 ("I've been waiting for a HuggingFace course my whole life." și "I hate this so much!"). Treceți-le prin model și verificați dacă obțineți aceeași logiți ca în secțiunea 2. Acum grupați-le împreună folosind token-ul de padding, apoi creați masca de atenție corespunzătoare. Verificați dacă obțineți aceleași rezultate atunci când parcurgeți modelul!
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/1.mdx
> +Apoi vom analiza API-ul tokenizer, care este cealaltă componentă principală a funcției `pipeline()`. Tokenizerii se ocupă de prima și ultima etapă de procesare, gestionând conversia de la text la int
```suggestion
Apoi vom analiza API-ul tokenizer, care este cealaltă componentă principală a funcției `pipeline()`. Tokenizerii se ocupă de prima și ultima etapă de procesare, gestionând conversia de la text la intrări numerice pentru rețeaua neuronală și conversia înapoi la text atunci când este necesar. În cele din urmă, vă vom arăta cum să vă ocupați de trimiterea mai multor propoziții printr-un model în cadrul unui batch pregătit, apoi vom încheia totul cu o examinare mai atentă a funcției  `tokenizer()`.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/2.mdx
> +- **Dimensiunea lotului**: Numărul de secvențe prelucrate simultan (2 în exemplul nostru).
```suggestion
- **Dimensiunea batch-ului**: Numărul de secvențe prelucrate simultan (2 în exemplul nostru).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +## Modelele așteaptă un lot de intrări[[modelele-așteaptă-un-lot-de-intrări]]
```suggestion
## Modelele așteaptă un batch de intrări[[modelele-așteaptă-un-batch-de-intrări]]
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +Gruparea în loturi este acțiunea de a trimite mai multe propoziții prin model, toate odată. Dacă aveți o singură propoziție, puteți crea un lot cu o singură secvență:
```suggestion
Gruparea în loturi este acțiunea de a trimite mai multe propoziții prin model, toate odată. Dacă aveți o singură propoziție, puteți crea un batch cu o singură secvență: 
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +Acesta este un lot de două secvențe identice!
```suggestion
Acesta este un batch de două secvențe identice!
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +Gruparea în loturi permite modelului să funcționeze atunci când îi furnizați mai multe secvențe. Utilizarea mai multor secvențe este la fel de simplă ca și crearea unui lot cu o singură secvență. Exi
```suggestion
Gruparea în loturi permite modelului să funcționeze atunci când îi furnizați mai multe secvențe. Utilizarea mai multor secvențe este la fel de simplă ca și crearea unui batch cu o singură secvență. Există însă o a doua problemă. Atunci când încercați să combinați două (sau mai multe) propoziții, acestea pot avea lungimi diferite. Dacă ați mai lucrat vreodată cu tensori, știți că aceștia trebuie să aibă o formă dreptunghiulară, deci nu veți putea converti direct lista de ID-uri de intrare într-un tensor. Pentru a rezolva această problemă, de obicei *umplem* datele de intrare.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +Acest lucru se datorează faptului că principala caracteristică a modelelor Transformer sunt straturile de atenție care *contextualizează* fiecare token. Acestea vor lua în considerare token-urile de
```suggestion
Acest lucru se datorează faptului că principala caracteristică a modelelor Transformer sunt straturile de atenție care *contextualizează* fiecare token. Acestea vor lua în considerare token-urile de umplutură, deoarece se ocupă de toate token-urile unei secvențe. Pentru a obține același rezultat atunci când trecem propoziții individuale de diferite lungimi prin model sau atunci când trecem un batch cu aceleași propoziții și același umplutură aplicată, trebuie să spunem acelor straturi de atenție să ignore token-urile de umplutură. Acest lucru se realizează prin utilizarea unei măști de atenție (attention mask).
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +Acum obținem aceeași logits pentru a doua propoziție din lot.
```suggestion
Acum obținem aceeași logits pentru a doua propoziție din batch.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +✏️ ** Încercați!** Convertiți această listă `batched_ids` într-un tensor și treceți-o prin modelul dumneavoastră. Verificați dacă obțineți aceleași logits ca înainte (dar de două ori)!
```suggestion
✏️ **Încercați!** Convertiți această listă `batched_ids` într-un tensor și treceți-o prin modelul dumneavoastră. Verificați dacă obțineți aceleași logits ca înainte (dar de două ori)!
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +✏️ ** Încercați!** Aplicați manual tokenizarea pe cele două propoziții utilizate în secțiunea 2 ("I've been waiting for a HuggingFace course my whole life." și "I hate this so much!"). Treceți-le pri
```suggestion
✏️ **Încercați!** Aplicați manual tokenizarea pe cele două propoziții utilizate în secțiunea 2 ("I've been waiting for a HuggingFace course my whole life." și "I hate this so much!"). Treceți-le prin model și verificați dacă obțineți aceeași logiți ca în secțiunea 2. Acum grupați-le împreună folosind token-ul de umplere, apoi creați masca de atenție corespunzătoare. Verificați dacă obțineți aceleași rezultate atunci când parcurgeți modelul!
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +# This line will fail.
```suggestion
# Aceasă linie va eșua.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/6.mdx
> +După cum vom vedea în câteva exemple de mai jos, această metodă este foarte eficientă. În primul rând, poate tokeniza o singură secvență:
```suggestion
După cum vom vedea în câteva exemple de mai jos, această metodă este foarte puternică. În primul rând, poate tokeniza o singură secvență:
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/6.mdx
> +Acesta poate umple în funcție de mai multe obiective:
```suggestion
Poate aplica padding în funcție de mai multe obiective:
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/6.mdx
> +Obiectul `tokenizer` poate gestiona conversia în tensori specifici framework-ului, care pot fi apoi trimiși direct la model. De exemplu, în următorul exemplu de cod, solicităm tokenizatorului să retu
```suggestion
Obiectul `tokenizer` poate gestiona conversia în tensori specifici framework-ului, care pot fi apoi trimiși direct la model. De exemplu, în următorul exemplu de cod, solicităm tokenizatorului să returneze tensori din diferite framework-uri - `„pt”` returnează tensori PyTorch, `„tf”` returnează tensori TensorFlow, iar `„np”` returnează matrici NumPy:
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/6.mdx
> +## Încheiere: De la tokenizer la model[[încheiere-de-la-tokenizator--model]]
```suggestion
## Încheiere: De la tokenizer la model[[încheiere-de-la-tokenizator-la-model]]
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/7.mdx
> +
```suggestion
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/7.mdx
> +Ați făcut o treabă excelentă dacă ați urmat cursul până aici! Pentru a sintetiza, în acest capitol ați:
```suggestion
Ai făcut o treabă excelentă urmând cursul până aici! Pentru a recapitula, în acest capitol:
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/7.mdx
> +- V-ați antrenat cu ajutorul metodelor versatile și configurabile ale tokenizatorului.
```suggestion
- Am învățat elementele de bază ale unui model Transformer.
- Am învățat ce formează un pipeline de tokenizare.
- Am văzut cum să utilizăm un model Transformer în practică.
- Am învățat cum să folosim un tokenizer pentru a converti textul în tensori care sunt inteligibili pentru model.
- Am configurat împreună un tokenizer și un model pentru a ajunge de la text la predicții.
- Am învățat limitările ID-urilor de intrare și am învățat despre attention masks.
- Am interacționt cu metode de tokenizare versatile și configurabile.
```

2024-11-14 18:52 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/8.mdx
can you also translate the quizes

2025-04-02 19:02 UTC, eduard-balamatiuc commented on chapters/rum/chapter2/5.mdx
> +✏️ ** Încercați!** Aplicați manual tokenizarea pe cele două propoziții utilizate în secțiunea 2 ("I've been waiting for a HuggingFace course my whole life." și "I hate this so much!"). Treceți-le pri
```suggestion
✏️ ** Încercați!** Aplicați manual tokenizarea pe cele două propoziții utilizate în secțiunea 2 ("I've been waiting for a HuggingFace course my whole life." și "I hate this so much!"). Treceți-le prin model și verificați dacă obțineți aceeași logiți ca în secțiunea 2. Acum grupați-le împreună folosind token-ul de padding, apoi creați masca de atenție corespunzătoare. Verificați dacă obțineți aceleași rezultate atunci când parcurgeți modelul!
```

2025-06-03 19:48 UTC, merged

2025-06-04 11:37 UTC, bytegrip commented
LGTM!